name: Run tests

on: [ push, pull_request ]

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build and test with Maven
        run: mvn -B -T 4 -Dmaven.source.skip=true -Dmaven.test.skip=false test
